package yang.home.HelloApp;

/**
* yang/home/HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, January 29, 2016 10:40:59 AM CST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public yang.home.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (yang.home.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = yang.home.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    yang.home.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return yang.home.HelloApp.HelloHelper.type ();
  }

}
